[package]
  cjc-version = "1.0.5"
  name = "cangjie_pj"
  description = "nothing here"
  version = "1.0.0"
  target-dir = ""
  output-type = "executable"
  compile-option = ""
  override-compile-option = ""
  link-option = ""
  package-configuration = {}

[dependencies]


[target]
  [target.x86_64-unknown-linux-gnu]
    [target.x86_64-unknown-linux-gnu.bin-dependencies]
      path-option = [ "${CANGJIE_STDX_PATH}/linux_x86_64_cjnative/dynamic/stdx" ]